name: Commitlint

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Lint commit messages
        run: nix shell nixpkgs#commitlint-rs --command bash .github/workflows/scripts/commitlint.sh
